#魔法専用保存領域。魔法のみ使用出し入れ可能なチェストです.
#/magicで使用可能です.
magicchest:
  use: false
#プレイヤー固有スキル機能です.
#/skillで編集できます.
skill:
  use: false
config:
  mysql:
    database: mincramagicrod
    port: 3306
    hostname: localhost
    username: 
    password: 